### ISSUE TITLE
[question] Advice on best way to sort by rating

### ISSUE THREAD

**Issue by ClementN** [renoki-co/rating#22]
Hello,

Can you, please, advice on what will be the best way to sort a model collection by rating? 

Thank you,

**Comment by rennokki** [comment]
Hey @ClementN, can you give some more info on what you're trying to achieve?

In case you want to filter by ratings for a specific model, you can just give it a shot by checking [relationship existence](https://laravel.com/docs/8.x/eloquent-relationships#querying-relationship-existence)

**Comment by ClementN** [comment]
Hello, @rennokki . 

Yes. Your suggestion pointed into the right direction. 

Thank you very much!
