### ISSUE TITLE
Error Installing rating

### ISSUE THREAD

**Issue by aksayed08** [renoki-co/rating#29]
macwin in ~/Downloads/robi-mylife-master/laravel  > composer require rennokki/rating
Using version ^3.0 for rennokki/rating
./composer.json has been updated
Running composer update rennokki/rating
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - rennokki/rating[3.0.0, ..., 3.0.1] require illuminate/database ^7.30|^8.23 -> found illuminate/database[v7.30.0, ..., v7.30.4, v8.23.1, ..., v8.42.1] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires rennokki/rating ^3.0 -> satisfiable by rennokki/rating[3.0.0, 3.0.1].

**Comment by rennokki** [comment]
Laravel version?
