### ISSUE TITLE
The average rating returned not correct.

### ISSUE THREAD

**Issue by Dennis-Mwea** [renoki-co/rating#31]
Am thinking the average rating should be a waited average. Not the average rating of total columns in the database. Something like:
```
∑𝑛𝑖=1𝑤𝑖⋅𝑎𝑖
----------
∑𝑛𝑖=1𝑤𝑖


1⋅5+2⋅3+3⋅1+4⋅17+5⋅2.         92 -       (Weighted sum)
-------------------------- = ---- 
5+3+1+17+2                    28      -  (Total sum)

**Comment by rennokki** [comment]
Does this mean that your model rated twice the same rateable model? This seems a flaw.

**Comment by Dennis-Mwea** [comment]
Not really. I have 3 models, User, Order and Courier (Courier delivery DB structure). A User can rate a Courier based on the Order he delivered. Assuming the 5 users rate the courier with a rating of 5 for 2 users, 3 for 2 users and 1 for one user, the courier rating can't be 5/5 but rather ```

**Comment by rennokki** [comment]
Based on your example, it seems like the table with ratings looks like:

- 5
- 5
- 3
- 3
- 1

The sum is `17`, with total rows of `5`. The expected average is `17/5` which is equivalent to `3.4`.

This seems a bit odd. Pulling the ratings [are expected to be working with the `->avg()` call](https://github.com/renoki-co/rating/blob/master/src/Traits/CanBeRated.php#L36).

Did you calculate the rating from the user's side? Did you call the average rating call like this?

```php
$user->averageRating();
$user->averageRating(Courier::class); 
```

**Comment by Dennis-Mwea** [comment]
No I pulled the changes from Courier side. $courier->averageRating(User::class) but the value I get is the average rating from db average not the weighted average
